services:
  auth-service:
    build:
      context: ./apps/micro-services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    
    volumes:
      - ./apps/micro-services/auth-service:/app
      

  auth-portal:
    build:
      context: ./apps/micro-frontends/auth-portal
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
  
    volumes:
      - ./apps/micro-frontends/auth-portal:/app
      
      - /app/node_modules
