name: Main CI Orchestrator

on:
  push:
    branches:
      - monorepo-dev
    paths:
      - 'apps/**'

jobs:
  # 1. ఏ ఫోల్డర్ లో మార్పులు జరిగాయో కనిపెట్టే జాబ్
  Changes-Detector:
    runs-on: ubuntu-latest
    outputs:
      auth-portal: ${{ steps.filter.outputs.auth-portal }}
      auth-service: ${{ steps.filter.outputs.auth-service }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            auth-portal:
              - 'apps/micro-frontends/auth-portal/**'
            auth-service:
              - 'apps/micro-services/auth-service/**'

  # 2. Auth Portal Flow (పైన ఉన్న రిజల్ట్ ని బట్టి రన్ అవుతుంది)
  Auth-Portal-Flow:
    needs: Changes-Detector
    if: needs.Changes-Detector.outputs.auth-portal == 'true'
    uses: ./.github/workflows/auth-portal-deploy.yml
    secrets: inherit

  # 3. Auth Service Flow
  Auth-Service-Flow:
    needs: Changes-Detector
    if: needs.Changes-Detector.outputs.auth-service == 'true'
    uses: ./.github/workflows/auth-service-deploy.yml
    secrets: inherit